# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(07100F)
$foreground = rgb(BBC9C8)
$color0 = rgb(232F2E)
$color1 = rgb(BC3A6D)
$color2 = rgb(2F8D5F)
$color3 = rgb(989B00)
$color4 = rgb(3A7ECD)
$color5 = rgb(CD3A91)
$color6 = rgb(00B7BF)
$color7 = rgb(BBC9C8)
$color8 = rgb(485151)
$color9 = rgb(E62F76)
$color10 = rgb(00994F)
$color11 = rgb(CBCF00)
$color12 = rgb(0075FF)
$color13 = rgb(FF0096)
$color14 = rgb(00F4FF)
$color15 = rgb(BBC9C8)
